#!/bin/bash
# career-ops user-layer backup — MANUAL ONLY. Run it yourself: scheduling/backup-user-layer.sh
#
# Deliberately not scheduled (2026-09-08, user decision): this never runs automatically.
# scheduling/io.career-ops.backup.plist is kept for reference but is NOT installed in
# ~/Library/LaunchAgents and must not be. Do not bootstrap it.
#
# Everything personal in this repo is gitignored (CV, profile, portals, tracker, reports,
# PDFs, contacts, plugin config) and existed only on this Mac until a `git clean -fdX`
# sweep wiped it on 2026-09-07. This mirrors that layer into the PRIVATE repo
# prasta1/backup-career under career-ops/ and pushes. Allowlist only: never .env,
# never node_modules, caches or logs. Run by hand any time: scheduling/backup-user-layer.sh
set -euo pipefail
SRC="$(cd "$(dirname "$0")/.." && pwd)"
# Derive the backup repo from THIS repo's location, not $HOME — the workspace lives on
# /Volumes/prasta, so the old $HOME path resolved to a directory that does not exist and
# the guard below exited 1 on every run (same folder-move breakage as meemeep, twice).
# Override with CAREER_OPS_BACKUP_REPO if the layout changes again.
REPO="${CAREER_OPS_BACKUP_REPO:-$(cd "$SRC/../.." && pwd)/backups/backup-career}"
DST="$REPO/career-ops"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
[ -d "$REPO/.git" ] || { echo "backup repo missing at $REPO — gh repo clone prasta1/backup-career there first"; exit 1; }
mkdir -p "$DST"

# Mirror the WHOLE repo (2026-09-08, user decision) minus four categories:
#   .git          — a nested repo cannot be committed into the backup repo
#   build output  — web/.next alone is 649M and is regenerated by `npm run build`
#   dependencies  — node_modules (461M in web/, 22M at root), restored from the lockfiles
#   secrets       — .env holds live GEMINI_API_KEY / OPENROUTER_API_KEY; .env.example
#                   IS mirrored, so a restore knows which keys to refill. Excluded on
#                   purpose: a private repo still keeps pushed blobs in history forever.
# Everything else goes, including files the previous allowlist silently skipped.
rsync -a --delete \
  --exclude='/.git/' \
  --exclude='node_modules/' \
  --exclude='/web/.next/' --exclude='/web/tsconfig.tsbuildinfo' \
  --exclude='.next/' --exclude='/dashboard/dist/' \
  --exclude='/.env' --exclude='/.envrc' \
  --exclude='*.log' --exclude='/data/cache/' --exclude='.DS_Store' \
  --exclude='/.claude/' \
  --exclude='/.playwright-mcp/' --exclude='.pytest_cache/' --exclude='__pycache__/' \
  "$SRC/" "$DST/"

# Belt and braces: .env is excluded above, but refuse to commit if a token slipped in anyway.
if grep -rIl -E 'pat-(na|eu)[0-9]-[0-9a-f]{8}|sk-[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{20,}|ntn_[A-Za-z0-9]{20,}' "$DST" 2>/dev/null | grep -q .; then
  echo "$(date '+%F %T') ABORT: token-like string found in mirror — not committing"; exit 2
fi

cd "$REPO"
git add -A -- career-ops   # scoped to the mirror dir, which rsync built from the allowlist above
if git diff --cached --quiet; then echo "$(date '+%F %T') no changes"; exit 0; fi
git commit -q -m "career-ops user layer $(date '+%F %H:%M')"
git push -q origin main
echo "$(date '+%F %T') pushed $(git rev-parse --short HEAD): $(git diff --stat HEAD~1 | tail -1)"
